ANÁLISE EXPLORATÓRIA DE DADOS :
LOJAS DE MATERIAL DE CONSTRUÇÃO - CONSTRUFÁCIL

In [7]:
import pandas as pd
import numpy as np
import plotly.express as px

In [8]:
# Carregar os dados do arquivo Excel
df = pd.read_excel("C:/Users/jcesa/OneDrive/Área de Trabalho/Análise de Dados e Dashboard - ConstruFacil/dados_construfacil.xlsx")

In [9]:
# Exibir as primeiras linhas do DataFrame para verificar os dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Venda             2000 non-null   object
 1   Data_Venda           2000 non-null   datetime64[ns]
 2   ID_Produto           2000 non-null   object
 3   Nome_Produto         2000 non-null   object
 4   Categoria_Produto    2000 non-null   object
 5   Preco_Unitario       2000 non-null   int64
 6   Quantidade_Vendida   2000 non-null   int64
 7   Valor_Total_Venda    2000 non-null   int64
 8   ID_Vendedor          2000 non-null   object
 9   Nome_Vendedor        2000 non-null   object
 10  ID_Loja              2000 non-null   object
 11  Nome_Loja            2000 non-null   object
 12  Cidade_Loja          2000 non-null   object
 13  Estado_Loja          2000 non-null   object
 14  Nivel_Estoque_Atual  2000 non-null   int64
 15  Custo_Produto        2000 non-null   int64
 16  Margem_Lucro         2000 non-null   int64
 17  Tipo_Cliente         2000 non-null   object
 18  Metodo_Pagamento     2000 non-null   object
dtypes: datetime64[ns](1), int64(6), object(12)
memory usage: 297.0+ KB

In [10]:
# Converter a coluna "Data_Venda" para o formato datetime
df["Data_Venda"] = pd.to_datetime(df["Data_Venda"], format = 'ISO8601')

In [11]:
#Retirando prefixos nos nomes dos vendedores
df['Nome_Vendedor'] = df['Nome_Vendedor'].str.replace(r'^[^.]+\.', '', regex=True).str.strip() # Remove tudo antes do primeiro ponto e espaços em branco
df["Nome_Vendedor"]
df

,ID_Venda,Data_Venda,ID_Produto,Nome_Produto,Categoria_Produto,Preco_Unitario,Quantidade_Vendida,Valor_Total_Venda,ID_Vendedor,Nome_Vendedor,ID_Loja,Nome_Loja,Cidade_Loja,Estado_Loja,Nivel_Estoque_Atual,Custo_Produto,Margem_Lucro,Tipo_Cliente,Metodo_Pagamento
0,VENDA00001,2024-11-22,PROD031,Rolo de Pintura,Tintas e Acessórios,17689,3,53067,VEND11,Ana Beatriz da Costa,LOJA03,ConstruFácil Centro,Curitiba,PR,188,12128,16683,Pessoa Física,Cartão de Crédito
1,VENDA00002,2024-03-29,PROD050,Quidem Premium,Louças e Metais Sanitários,20119,4,80476,VEND11,Ana Beatriz da Costa,LOJA03,ConstruFácil Centro,Curitiba,PR,605,11195,35696,Pessoa Física,Boleto
2,VENDA00003,2024-01-26,PROD037,Serra Mármore,Ferramentas,23037,5,115185,VEND06,Melissa Sampaio,LOJA01,ConstruFácil Zona Sul,Campinas,SP,240,16905,3066,Pessoa Jurídica,Débito
3,VENDA00004,2023-02-27,PROD048,Azulejo Decorado,Revestimentos (Pisos e Azulejos),5041,38,191558,VEND15,Joaquim da Cruz,LOJA02,ConstruFácil Comercial,Salvador,BA,607,3282,66842,Pessoa Jurídica,Dinheiro
4,VENDA00005,2024-02-10,PROD004,Cano PVC 100mm,Hidráulica,10825,7,75775,VEND12,Brayan Montenegro,LOJA05,ConstruFácil Comercial,Porto Alegre,RS,951,8273,17864,Pessoa Física,Débito
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,VENDA01996,2024-07-19,PROD038,Rolo de Pintura,Tintas e Acessórios,21051,3,63153,VEND02,João Lucas da Conceição,LOJA05,ConstruFácil Comercial,Porto Alegre,RS,545,12176,26625,Pessoa Jurídica,Dinheiro
1996,VENDA01997,2023-06-13,PROD018,Tinta Acrílica Premium 18L,Tintas e Acessórios,20296,5,10148,VEND10,Murilo Sousa,LOJA01,ConstruFácil Zona Sul,Campinas,SP,394,1497,2663,Pessoa Jurídica,Cartão de Crédito
1997,VENDA01998,2024-07-14,PROD022,Illum Standard,Portas e Janelas,14164,6,84984,VEND13,Luiz Gustavo Brito,LOJA01,ConstruFácil Zona Sul,Campinas,SP,343,7487,40062,Pessoa Jurídica,Dinheiro
1998,VENDA01999,2024-03-07,PROD018,Tinta Acrílica Premium 18L,Tintas e Acessórios,17494,37,647278,VEND15,Joaquim da Cruz,LOJA01,ConstruFácil Zona Sul,Campinas,SP,394,15358,79032,Pessoa Jurídica,Cartão de Crédito
1999,VENDA02000,2023-11-24,PROD039,Tempore Standard,Louças e Metais Sanitários,4508,1,4508,VEND05,Rael Mendes,LOJA04,ConstruFácil Zona Sul,Fortaleza,CE,732,3532,976,Pessoa Jurídica,Débito

In [12]:
# Exibir informações sobre o DataFrame, como tipos de dados e contagem de valores não nulos
df.describe()

,Data_Venda,Preco_Unitario,Quantidade_Vendida,Valor_Total_Venda,Nivel_Estoque_Atual,Custo_Produto,Margem_Lucro
count,2000,2000.000000,2000.000000,2.000000e+03,2000.000000,2000.000000,2000.00000
mean,2023-12-26 23:18:14.400000256,11623.919000,23.977000,7.318014e+04,539.835500,7649.871500,23605.95350
min,2023-01-01 00:00:00,19.000000,1.000000,1.150000e+02,127.000000,12.000000,68.00000
25%,2023-06-27 00:00:00,3710.250000,4.000000,1.216750e+04,379.000000,2328.750000,3852.00000
50%,2023-12-27 00:00:00,11130.000000,7.000000,3.231350e+04,557.000000,7350.500000,10684.50000
75%,2024-06-24 06:00:00,16602.000000,10.000000,9.651375e+04,711.500000,10896.500000,30092.25000
max,2024-12-31 00:00:00,75456.000000,498.000000,1.020096e+06,951.000000,49902.000000,312384.00000
std,NaN,10532.349408,71.142548,1.081090e+05,224.224568,7005.759237,33849.62021

In [13]:
# Verificar a quantidade de valores nulos em cada coluna
dados_nulos = df.notnull().sum()
dados_ausentes = df.isnull().sum()
checagem_valores_nulos_e_ausentes = pd.DataFrame({'Valores Não Nulos': dados_nulos, 'Valores Ausentes': dados_ausentes})
checagem_valores_nulos_e_ausentes

                     Valores Não Nulos  Valores Ausentes
ID_Venda                          2000                 0
Data_Venda                        2000                 0
ID_Produto                        2000                 0
Nome_Produto                      2000                 0
Categoria_Produto                 2000                 0
Preco_Unitario                    2000                 0
Quantidade_Vendida                2000                 0
Valor_Total_Venda                 2000                 0
ID_Vendedor                       2000                 0
Nome_Vendedor                     2000                 0
ID_Loja                           2000                 0
Nome_Loja                         2000                 0
Cidade_Loja                       2000                 0
Estado_Loja                       2000                 0
Nivel_Estoque_Atual               2000                 0
Custo_Produto                     2000                 0
Margem_Lucro                      2000                 0
Tipo_Cliente                      2000                 0
Metodo_Pagamento                  2000                 0

In [14]:
# Análise de Quantidade de Vendas por Método de Pagamento
quanti_venda_metodo_pagamento = df["Metodo_Pagamento"].value_counts().reset_index()
quanti_venda_metodo_pagamento.columns = ["Metodo_Pagamento", "Quantidade_Vendas"]
quanti_venda_metodo_pagamento

    Metodo_Pagamento  Quantidade_Vendas
0             Boleto                415
1           Dinheiro                411
2                Pix                401
3             Débito                387
4  Cartão de Crédito                386

In [15]:
# Análise de Valor Total de Vendas por Método de Pagamento
total_vendas_metodo_pagamento = df["Valor_Total_Venda"].groupby(df["Metodo_Pagamento"]).sum().reset_index()
total_vendas_metodo_pagamento

    Metodo_Pagamento  Valor_Total_Venda
0             Boleto           31920455
1  Cartão de Crédito           29339596
2           Dinheiro           28217975
3             Débito           29826676
4                Pix           27055574

In [16]:
# Criar uma tabela combinando a quantidade de vendas e o valor total de vendas por método de pagamento
Tabela_metodos_vendas = pd.DataFrame({
    "Metodo_Pagamento": quanti_venda_metodo_pagamento["Metodo_Pagamento"],
    "Quantidade_Vendas": quanti_venda_metodo_pagamento["Quantidade_Vendas"],
    "Valor_Total_Vendas": total_vendas_metodo_pagamento["Valor_Total_Venda"].round(2)
})
Tabela_metodos_vendas

    Metodo_Pagamento  Quantidade_Vendas  Valor_Total_Vendas
0             Boleto                415            31920455
1           Dinheiro                411            29339596
2                Pix                401            28217975
3             Débito                387            29826676
4  Cartão de Crédito                386            27055574

In [85]:
# Criar um gráfico de barras para a quantidade de vendas por método de pagamento
fig_barras = px.bar(
    Tabela_metodos_vendas,
    x='Metodo_Pagamento',
    y='Quantidade_Vendas',
    title='Quantidade de Vendas por Método de Pagamento',
    labels={'Metodo_Pagamento': 'Método de Pagamento', 'Quantidade_Vendas': 'Quantidade de Vendas'},
    color='Metodo_Pagamento', # Opcional: colore as barras por método de pagamento
    template='plotly_white', # Define um tema para o gráfico
    text='R$ '+Tabela_metodos_vendas['Valor_Total_Vendas'].astype(str) # Exibe o valor total de vendas em cada barra   
    
)

fig_barras.show()

In [18]:
# Análise de Quantidade de Vendas por Vendedor
vendedor = df[["ID_Vendedor", "Nome_Vendedor"]].value_counts().reset_index(name="Quantidade_Vendas")
vendedor.columns = ["ID_Vendedor", "Nome_Vendedor", "Quantidade_Vendas"]
vendedor

   ID_Vendedor            Nome_Vendedor  Quantidade_Vendas
0       VEND05              Rael Mendes                154
1       VEND10             Murilo Sousa                146
2       VEND03         Beatriz da Rocha                144
3       VEND09             Danilo Costa                140
4       VEND01           Benício Garcia                135
5       VEND08  Arthur Gabriel da Rocha                133
6       VEND15          Joaquim da Cruz                132
7       VEND04           Marina Moreira                131
8       VEND14           Benício Farias                131
9       VEND06          Melissa Sampaio                130
10      VEND11     Ana Beatriz da Costa                129
11      VEND07   Maria Luísa Nascimento                127
12      VEND02  João Lucas da Conceição                126
13      VEND13       Luiz Gustavo Brito                126
14      VEND12        Brayan Montenegro                116

In [19]:
# Análise de Valor Total de Vendas por Vendedor
total_valor_vendedor = df["Valor_Total_Venda"].groupby(df["ID_Vendedor"]).sum().reset_index()
total_valor_vendedor.columns = ["ID_Vendedor", "Valor_Total_Vendas"]
total_valor_vendedor

   ID_Vendedor  Valor_Total_Vendas
0       VEND01             9641150
1       VEND02            11876788
2       VEND03            11439181
3       VEND04             8137600
4       VEND05            12114011
5       VEND06             9619798
6       VEND07            11243841
7       VEND08            11118237
8       VEND09             8731621
9       VEND10             8303562
10      VEND11            10126555
11      VEND12             8204033
12      VEND13             7421885
13      VEND14             9516164
14      VEND15             8865850

In [114]:
# Criar uma tabela combinando a quantidade de vendas e o valor total de vendas por vendedor
Vendedores_por_vendas = pd.DataFrame({
    "ID_Vendedor": vendedor["ID_Vendedor"],
    "Nome_Vendedor": vendedor["Nome_Vendedor"],
    "Quantidade_Vendas": vendedor["Quantidade_Vendas"],
    "Valor_Total_Vendas": total_valor_vendedor["Valor_Total_Vendas"].round(2)
})

Vendedores_por_vendas = Vendedores_por_vendas.sort_values(by="Valor_Total_Vendas", ascending=False).reset_index(drop=True) # Ordena os vendedores por valor total de vendas em ordem crescente
Vendedores_por_vendas['Valor_Total_Vendas'] = Vendedores_por_vendas['Valor_Total_Vendas'] # Formata o valor total de vendas como moeda brasileira
Vendedores_por_vendas.head(10) # Exibe os 10 vendedores com maior valor total de vendas

  ID_Vendedor            Nome_Vendedor  Quantidade_Vendas  Valor_Total_Vendas
0      VEND01           Benício Garcia                135            12114011
1      VEND10             Murilo Sousa                146            11876788
2      VEND03         Beatriz da Rocha                144            11439181
3      VEND15          Joaquim da Cruz                132            11243841
4      VEND04           Marina Moreira                131            11118237
5      VEND11     Ana Beatriz da Costa                129            10126555
6      VEND05              Rael Mendes                154             9641150
7      VEND08  Arthur Gabriel da Rocha                133             9619798
8      VEND13       Luiz Gustavo Brito                126             9516164
9      VEND12        Brayan Montenegro                116             8865850

In [116]:
# Criar um gráfico de barras para a quantidade de vendas por vendedor
fig_barras = px.bar(
    Vendedores_por_vendas, 
    x='Nome_Vendedor',
    y='Valor_Total_Vendas',
    title='Total de Vendas por Vendedor',
    labels={'Nome_Vendedor': 'Nome do Vendedor', 'Valor_Total_Vendas': 'Valor Total de Vendas'},
    color='Nome_Vendedor', # Opcional: colore as barras por nome do vendedor
    template='plotly_white', # Define um tema para o gráfico
    text=' R$ ' + Vendedores_por_vendas['Valor_Total_Vendas'].astype(str) # Exibe o valor total de vendas em cada barra, formatado como moeda brasileira
    
)

fig_barras.show()

In [50]:
categoria_produto = df["Categoria_Produto"].value_counts().reset_index(name="Quantidade_Vendas")
categoria_produto_valor_vendas = df["Valor_Total_Venda"].groupby(df["Categoria_Produto"]).sum().reset_index()
categoria_vendas = pd.DataFrame({
    "Categoria_Produto": categoria_produto["Categoria_Produto"],
    "Quantidade_Vendas": categoria_produto["Quantidade_Vendas"],
    "Valor_Total_Vendas": categoria_produto_valor_vendas["Valor_Total_Venda"].round(2)
})

categoria_vendas = categoria_vendas.sort_values(by="Valor_Total_Vendas", ascending=False)
categoria_vendas

                   Categoria_Produto  Quantidade_Vendas  Valor_Total_Vendas
13                        Hidráulica                 76            39997632
10             Cimentos e Argamassas                 91            20781123
3         Louças e Metais Sanitários                183            18461702
9                        Ferramentas                104            10936845
6                   Tijolos e Blocos                117            10090667
5   Revestimentos (Pisos e Azulejos)                141             9817309
12                   Telhas e Calhas                 84             8236325
7               Madeiras e Ferragens                113             5957504
8     Material Básico (Areia, Brita)                113             5232544
4          Equipamentos de Segurança                150             5075123
2                   Portas e Janelas                207             4794802
11                          Elétrica                 90             4004934
1                 Impermeabilizantes                232             1506565
0                Tintas e Acessórios                299             1467201

In [53]:
fig_barras = px.bar(
    categoria_vendas,
    x='Categoria_Produto',  
    y='Valor_Total_Vendas',
    title='Valor Total de Vendas por Categoria de Produto',  
    labels={'Categoria_Produto': 'Categoria de Produto', 'Valor_Total_Vendas': 'Valor Total de Vendas'},
    color='Categoria_Produto', # Opcional: colore as barras por categoria de produto
    template='plotly_white', # Define um tema para o gráfico
    text=' R$ ' + categoria_vendas['Valor_Total_Vendas'].astype(str) + ' (' + categoria_vendas['Quantidade_Vendas'].astype(str) + ' vendas)' # Exibe o valor total de vendas em cada barra, formatado como moeda brasileira
)

fig_barras.show()

ANÁLISE FINANCEIRA

Determinar Lucro ou Prejuízo

In [24]:
# Análise de Vendas Mensais
df.head()

,ID_Venda,Data_Venda,ID_Produto,Nome_Produto,Categoria_Produto,Preco_Unitario,Quantidade_Vendida,Valor_Total_Venda,ID_Vendedor,Nome_Vendedor,ID_Loja,Nome_Loja,Cidade_Loja,Estado_Loja,Nivel_Estoque_Atual,Custo_Produto,Margem_Lucro,Tipo_Cliente,Metodo_Pagamento
0,VENDA00001,2024-11-22,PROD031,Rolo de Pintura,Tintas e Acessórios,17689,3,53067,VEND11,Ana Beatriz da Costa,LOJA03,ConstruFácil Centro,Curitiba,PR,188,12128,16683,Pessoa Física,Cartão de Crédito
1,VENDA00002,2024-03-29,PROD050,Quidem Premium,Louças e Metais Sanitários,20119,4,80476,VEND11,Ana Beatriz da Costa,LOJA03,ConstruFácil Centro,Curitiba,PR,605,11195,35696,Pessoa Física,Boleto
2,VENDA00003,2024-01-26,PROD037,Serra Mármore,Ferramentas,23037,5,115185,VEND06,Melissa Sampaio,LOJA01,ConstruFácil Zona Sul,Campinas,SP,240,16905,3066,Pessoa Jurídica,Débito
3,VENDA00004,2023-02-27,PROD048,Azulejo Decorado,Revestimentos (Pisos e Azulejos),5041,38,191558,VEND15,Joaquim da Cruz,LOJA02,ConstruFácil Comercial,Salvador,BA,607,3282,66842,Pessoa Jurídica,Dinheiro
4,VENDA00005,2024-02-10,PROD004,Cano PVC 100mm,Hidráulica,10825,7,75775,VEND12,Brayan Montenegro,LOJA05,ConstruFácil Comercial,Porto Alegre,RS,951,8273,17864,Pessoa Física,Débito

In [70]:
# Análise de Lucro Total e Total de Vendas
df["custo_total"] = df["Custo_Produto"] * df["Quantidade_Vendida"] # Calcula o custo total multiplicando o custo do produto pela quantidade vendida
df["lucro"] = df["Valor_Total_Venda"] - df["custo_total"] # Calcula o lucro subtraindo o custo total do valor total de venda
df["resultado"] = df["lucro"].apply(lambda x: "Lucro" if x > 0 else "Prejuízo") # Classifica o resultado como "Lucro" ou "Prejuízo" com base no valor do lucro
df.head(10)

,ID_Venda,Data_Venda,ID_Produto,Nome_Produto,Categoria_Produto,Preco_Unitario,Quantidade_Vendida,Valor_Total_Venda,ID_Vendedor,Nome_Vendedor,...,Cidade_Loja,Estado_Loja,Nivel_Estoque_Atual,Custo_Produto,Margem_Lucro,Tipo_Cliente,Metodo_Pagamento,custo_total,lucro,resultado
0,VENDA00001,2024-11-22,PROD031,Rolo de Pintura,Tintas e Acessórios,17689,3,53067,VEND11,Ana Beatriz da Costa,...,Curitiba,PR,188,12128,16683,Pessoa Física,Cartão de Crédito,36384,16683,Lucro
1,VENDA00002,2024-03-29,PROD050,Quidem Premium,Louças e Metais Sanitários,20119,4,80476,VEND11,Ana Beatriz da Costa,...,Curitiba,PR,605,11195,35696,Pessoa Física,Boleto,44780,35696,Lucro
2,VENDA00003,2024-01-26,PROD037,Serra Mármore,Ferramentas,23037,5,115185,VEND06,Melissa Sampaio,...,Campinas,SP,240,16905,3066,Pessoa Jurídica,Débito,84525,30660,Lucro
3,VENDA00004,2023-02-27,PROD048,Azulejo Decorado,Revestimentos (Pisos e Azulejos),5041,38,191558,VEND15,Joaquim da Cruz,...,Salvador,BA,607,3282,66842,Pessoa Jurídica,Dinheiro,124716,66842,Lucro
4,VENDA00005,2024-02-10,PROD004,Cano PVC 100mm,Hidráulica,10825,7,75775,VEND12,Brayan Montenegro,...,Porto Alegre,RS,951,8273,17864,Pessoa Física,Débito,57911,17864,Lucro
5,VENDA00006,2024-09-26,PROD040,Possimus Básico,Madeiras e Ferragens,5382,9,48438,VEND05,Rael Mendes,...,Campinas,SP,709,337,18108,Pessoa Jurídica,Boleto,3033,45405,Lucro
6,VENDA00007,2023-02-07,PROD040,Possimus Básico,Madeiras e Ferragens,4945,4,1978,VEND05,Rael Mendes,...,Campinas,SP,709,3479,5864,Pessoa Física,Boleto,13916,-11938,Prejuízo
7,VENDA00008,2024-04-04,PROD006,Quia Básico,"Material Básico (Areia, Brita)",10856,7,75992,VEND09,Danilo Costa,...,Curitiba,PR,385,6633,29561,Pessoa Física,Pix,46431,29561,Lucro
8,VENDA00009,2023-08-04,PROD016,Laudantium Standard,Louças e Metais Sanitários,1089,3,3267,VEND08,Arthur Gabriel da Rocha,...,Salvador,BA,284,7327,10689,Pessoa Física,Boleto,21981,-18714,Prejuízo
9,VENDA00010,2024-09-13,PROD043,Accusamus Básico,"Material Básico (Areia, Brita)",4293,3,12879,VEND07,Maria Luísa Nascimento,...,Fortaleza,CE,697,2458,5505,Pessoa Física,Dinheiro,7374,5505,Lucro

In [26]:
# Análise de Lucro Total e Total de Vendas
lucro_total = df["lucro"].sum()
total_vendas = df["Valor_Total_Venda"].sum()
print(f"Lucro total: R$ {lucro_total:,.2f}")
print(f"Total de vendas: R$ {total_vendas:,.2f}")

Lucro total: R$ 23,174,734.00
Total de vendas: R$ 146,360,276.00

In [27]:
# Análise de Vendas Mensais
vendas_mensais = df.groupby(pd.Grouper(key="Data_Venda", freq="M"))["Valor_Total_Venda"].sum()
vendas_mensais = pd.DataFrame({
    "Data_Venda": vendas_mensais.index,
    "Valor_Total_Venda": vendas_mensais.values.round(2)
})

vendas_mensais

   Data_Venda  Valor_Total_Venda
0  2023-01-31            6914409
1  2023-02-28            6522967
2  2023-03-31            8235739
3  2023-04-30            4657069
4  2023-05-31            5587080
5  2023-06-30            5640628
6  2023-07-31            4817829
7  2023-08-31            7336925
8  2023-09-30            5975174
9  2023-10-31            6395349
10 2023-11-30            5420894
11 2023-12-31            6162118
12 2024-01-31            5734304
13 2024-02-29            5081859
14 2024-03-31            5641867
15 2024-04-30            6248552
16 2024-05-31            7214767
17 2024-06-30            6610422
18 2024-07-31            7976880
19 2024-08-31            6910241
20 2024-09-30            4651311
21 2024-10-31            4222982
22 2024-11-30            6007109
23 2024-12-31            6393801

In [28]:
# Cálculo da média móvel de 3 meses para as vendas mensais
# A média móvel de 3 meses é calculada usando a função rolling() do pandas, que cria uma janela deslizante de 3 meses sobre os dados de vendas mensais. A função mean() é aplicada para calcular a média dentro dessa janela, e o resultado é arredondado para 2 casas decimais usando round(2).
# A média móvel é uma técnica de suavização que ajuda a identificar tendências subjacentes nos dados, reduzindo o impacto de flutuações sazonais ou ruídos. No contexto das vendas mensais, a média móvel de 3 meses pode ajudar a destacar tendências de crescimento ou declínio nas vendas ao longo do tempo, proporcionando uma visão mais clara do desempenho geral da loja.
# O resultado é um DataFrame que contém as datas de venda e as respectivas médias móveis de vendas mensais, permitindo uma análise mais aprofundada das tendências de vendas ao longo do tempo.
vendas_mensais_ma = vendas_mensais.set_index("Data_Venda")["Valor_Total_Venda"].rolling(3).mean().round(2)
vendas_mensais_ma

vendas_mensais_ma = pd.DataFrame({
    "Data_Venda": vendas_mensais_ma.index,
    "Média_Móvel_3_Meses": vendas_mensais_ma.values
})

vendas_mensais_ma

   Data_Venda  Média_Móvel_3_Meses
0  2023-01-31                  NaN
1  2023-02-28                  NaN
2  2023-03-31           7224371.67
3  2023-04-30           6471925.00
4  2023-05-31           6159962.67
5  2023-06-30           5294925.67
6  2023-07-31           5348512.33
7  2023-08-31           5931794.00
8  2023-09-30           6043309.33
9  2023-10-31           6569149.33
10 2023-11-30           5930472.33
11 2023-12-31           5992787.00
12 2024-01-31           5772438.67
13 2024-02-29           5659427.00
14 2024-03-31           5486010.00
15 2024-04-30           5657426.00
16 2024-05-31           6368395.33
17 2024-06-30           6691247.00
18 2024-07-31           7267356.33
19 2024-08-31           7165847.67
20 2024-09-30           6512810.67
21 2024-10-31           5261511.33
22 2024-11-30           4960467.33
23 2024-12-31           5541297.33

In [119]:
# Criar um gráfico combinando vendas mensais e média móvel
fig = px.bar(
    x=vendas_mensais['Data_Venda'],
    y=[vendas_mensais['Valor_Total_Venda'], vendas_mensais_ma['Média_Móvel_3_Meses']],
    title='Vendas Mensais vs Média Móvel Simples (3 meses)',
    labels={'x': 'Mês', 'value': 'Valor (R$)'},
    barmode='group',
    template='plotly_white'
)

# Adicionar valores formatados como moeda nas barras
fig.data[0].text = 'R$ ' + (vendas_mensais['Valor_Total_Venda'].round(2).astype(str))
fig.data[0].textposition = 'inside'
fig.data[0].name = 'Vendas Mensais'

fig.data[1].text = 'R$ ' + (vendas_mensais_ma['Média_Móvel_3_Meses'].round(2).astype(str))
fig.data[1].textposition = 'inside'
fig.data[1].name = 'Média Móvel Simples(3 meses)'

fig.show()

Usando projeção simpleas (Média Móvel Simples)

Utilizando 3 meses para obtenção da média para a projeção

In [56]:
# Análise de Lucro por Produto
lucro_produto = (
    df.groupby("Nome_Produto")["lucro"]# Agrupa os dados por nome do produto e seleciona a coluna de lucro
    .sum() # Calcula a soma do lucro para cada produto
    .reset_index()   # Reseta o índice para transformar o resultado em um DataFrame
    .sort_values(by="lucro", ascending=False) # Ordena os produtos pelo lucro total em ordem decrescente
    
)

lucro_produto = pd.DataFrame({
    "Nome_Produto": lucro_produto["Nome_Produto"], # Seleciona a coluna de nome do produto
    "Lucro_Total (R$)":lucro_produto["lucro"].round(2) # Seleciona a coluna de lucro total e arredonda para 2 casas decimais
})

lucro_produto.head(5) # Exibe os 10 produtos com maior lucro total

                    Nome_Produto  Lucro_Total (R$)
38    Tinta Acrílica Premium 18L           5472633
20  Piso Cerâmico Antiderrapante           2696021
31                 Serra Mármore           2637911
21        Piso Porcelanato 60x60           2116889
30               Rolo de Pintura           1830184

In [58]:
# Criar funil com valores formatados em moeda brasileira (R$) sem duplicação
top5 = lucro_produto.head(5).copy()
top5['Lucro_Formatado'] = top5['Lucro_Total (R$)'].apply(
    lambda v: f"R$ {v:,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')
)

fig_funil = px.funnel(
    top5,
    x='Lucro_Total (R$)',
    y='Nome_Produto',
    template='plotly_white',
    title='TOP 5 - Produtos mais lucrativos',
    labels={'Lucro_Total (R$)': 'Lucro Total (R$)', 'Nome_Produto': 'Nome do Produto'} # Personalizar os rótulos dos eixos
)

# Exibir apenas o texto formatado dentro dos funis e remover o valor bruto do hover
fig_funil.data[0].text = top5['Lucro_Formatado'] # Exibir apenas o texto formatado dentro dos funis
fig_funil.data[0].textposition = 'inside'# Exibir apenas o texto formatado dentro dos funis
fig_funil.update_traces(texttemplate='%{text}', hovertemplate='Produto=%{y}<extra></extra>') # Remove o valor bruto do hover

fig_funil.show()

INSIGHTS POSSÍVEIS:

* Produto mais estratégico

* Produto que merece mais estoque e marketing

In [71]:
produtos_prejuizo = (
    df.groupby("Nome_Produto")["lucro"]
    .sum()
    .reset_index()
    .sort_values(by="lucro", ascending=True)  # Mudado para ascending=True
)

produtos_prejuizo = pd.DataFrame({
    "Nome_Produto": produtos_prejuizo["Nome_Produto"],
    "Prejuízo": produtos_prejuizo["lucro"]
})

produtos_prejuizo.head(5)  # Exibe os 5 produtos com menor lucro total

            Nome_Produto  Prejuízo
40  Torneira Monocomando   -769668
5         Cano PVC 100mm   -257097
16   Laudantium Standard   -207123
10          Harum Básico   -145774
29         Rem Reforçado   -143099

In [84]:
# Criar funil com valores formatados em moeda brasileira (R$) sem duplicação
down5 = produtos_prejuizo.head(5).copy()
down5['Lucro_Formatado'] = down5['Prejuízo'].apply(
    lambda v: f"R$ {abs(v):,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.') if v >= 0
    else f"-R$ {abs(v):,.2f}".replace(',', 'X').replace('.', ',').replace('X', '.')
)

down5['Lucro_Absoluto'] = down5['Prejuízo'].abs()

fig_funil = px.funnel(
    down5,
    x='Lucro_Absoluto',
    y='Nome_Produto',
    template='plotly_white',
    title='Produtos que deram prejuízo',   
    labels={'Lucro_Absoluto': 'Lucro (R$)', 'Nome_Produto': 'Nome do Produto'}
)

fig_funil.data[0].text = down5['Lucro_Formatado'].values
fig_funil.data[0].textposition = 'inside'
fig_funil.update_traces(texttemplate='%{text}', hovertemplate='Produto=%{y}<extra></extra>')

fig_funil.show()

INSIGHTS POSSÍVEIS:

1. Preço mal definido

2. Custo alto

3. Produto encalhado

PROJEÇÃO DE LUCRATIVIDADE

In [34]:
lucro_mensal = df.groupby(pd.Grouper(key='Data_Venda', freq='M'))['lucro'].sum()
lucro_mensal = pd.DataFrame({
    'Data_Venda': lucro_mensal.index,
    'Lucro_Mensal': lucro_mensal.values.round(2)
})

lucro_mensal

   Data_Venda  Lucro_Mensal
0  2023-01-31       1970170
1  2023-02-28       1294487
2  2023-03-31       1068742
3  2023-04-30        128400
4  2023-05-31        705378
5  2023-06-30       1005137
6  2023-07-31        514217
7  2023-08-31        719629
8  2023-09-30       1184670
9  2023-10-31        740773
10 2023-11-30        409916
11 2023-12-31        556767
12 2024-01-31        849521
13 2024-02-29       1377711
14 2024-03-31        670567
15 2024-04-30        541843
16 2024-05-31       1205228
17 2024-06-30       1250403
18 2024-07-31       1867276
19 2024-08-31       1688125
20 2024-09-30        612296
21 2024-10-31        666759
22 2024-11-30        565310
23 2024-12-31       1581409

In [35]:
lucro_mensal_ma = lucro_mensal.set_index("Data_Venda")["Lucro_Mensal"].rolling(3).mean().round(2)
lucro_mensal_ma = pd.DataFrame({
    'Data_Venda': lucro_mensal_ma.index,
    'Média_Móvel_3_Meses': lucro_mensal_ma.values
})
lucro_mensal_ma

   Data_Venda  Média_Móvel_3_Meses
0  2023-01-31                  NaN
1  2023-02-28                  NaN
2  2023-03-31           1444466.33
3  2023-04-30            830543.00
4  2023-05-31            634173.33
5  2023-06-30            612971.67
6  2023-07-31            741577.33
7  2023-08-31            746327.67
8  2023-09-30            806172.00
9  2023-10-31            881690.67
10 2023-11-30            778453.00
11 2023-12-31            569152.00
12 2024-01-31            605401.33
13 2024-02-29            927999.67
14 2024-03-31            965933.00
15 2024-04-30            863373.67
16 2024-05-31            805879.33
17 2024-06-30            999158.00
18 2024-07-31           1440969.00
19 2024-08-31           1601934.67
20 2024-09-30           1389232.33
21 2024-10-31            989060.00
22 2024-11-30            614788.33
23 2024-12-31            937826.00

In [36]:
# Criar um gráfico combinando lucro mensal e média móvel
fig = px.bar(
    x=lucro_mensal['Data_Venda'],
    y=[lucro_mensal['Lucro_Mensal'], lucro_mensal_ma['Média_Móvel_3_Meses']],
    title='Lucro Mensal vs Média Móvel Simples (3 meses)',
    labels={'x': 'Mês', 'value': 'Lucro (R$)'},
    barmode='group',
    template='plotly_dark'
)

# Adicionar valores formatados como moeda nas barras
fig.data[0].text = ' R$ ' + (lucro_mensal['Lucro_Mensal'].round(2).astype(str))
fig.data[0].textposition = 'inside'
fig.data[0].name = 'Lucro Mensal'

fig.data[1].text = ' R$ ' + (lucro_mensal_ma['Média_Móvel_3_Meses'].round(2).astype(str))
fig.data[1].textposition = 'inside'
fig.data[1].name = 'Média Móvel Simples(3 meses)'

fig.show()

A empresa está ficando mais lucrativa?

Há sazonalidade?

Vale manter certos produtos?